/*
 * MIT License
 *
 * Copyright (c) 2018 Michał
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package AlgoWiedenski;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 *
 * @author michal
 */
public class Wegier extends javax.swing.JPanel {

    private Algorytm alg;

    /**
     * Creates new form Wegier
     */
    public Wegier() {
        initComponents();
        alg = new Algorytm(this);
    }

    public JLabel getJLMsg() {
        return JLMsg;
    }

    public JButton getJBNext() {
        return JBNext;
    }

    public JTextPane getJTP() {
        return JTP;
    }

    public JTextPane getJTPMask() {
        return JTPMask;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTP = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTPMask = new javax.swing.JTextPane();
        JBMask = new javax.swing.JButton();
        JLMsg = new javax.swing.JLabel();
        JBML = new javax.swing.JButton();

        JBNext.setText("Next");
        JBNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNextActionPerformed(evt);
            }
        });

        JTP.setText("20\t40\t10\t50\n100\t80\t30\t40\n10\t5\t60\t20\n70\t30\t10\t25\n");
        jScrollPane1.setViewportView(JTP);

        jScrollPane2.setViewportView(JTPMask);

        JBMask.setText("Show Masked zeros");
        JBMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMaskActionPerformed(evt);
            }
        });

        JBML.setText("Show markes lines");
        JBML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBMask)
                        .addGap(45, 45, 45)
                        .addComponent(JBML)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(JLMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBNext)
                    .addComponent(JLMsg))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBMask)
                    .addComponent(JBML))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNextActionPerformed
        // TODO add your handling code here:        
        JTP.setText(alg.next());

    }//GEN-LAST:event_JBNextActionPerformed

    private void JBMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMaskActionPerformed
        // TODO add your handling code here:
        JTPMask.setText(alg.TestPaintMZ());
    }//GEN-LAST:event_JBMaskActionPerformed

    private void JBMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMLActionPerformed
        // TODO add your handling code here:
        JTPMask.setText(alg.TestPaintML());
    }//GEN-LAST:event_JBMLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBML;
    private javax.swing.JButton JBMask;
    private javax.swing.JButton JBNext;
    private javax.swing.JLabel JLMsg;
    private javax.swing.JTextPane JTP;
    private javax.swing.JTextPane JTPMask;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
